# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Morning
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    # GitHub Actions 使用的是UTC时间，比北京时间慢八个小时
    - cron: '59 23 * * *'

jobs:
  Morning:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Morning script
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sed -i "s/ServerChanKey/${{ secrets.ServerChanKey }}/g" morning.py
        python ./morning.py >> /dev/null